version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  db:
    image: couchbase:latest
    ports:
      - 8091-8094:8091-8094
      - 11210-11211:11210-11211
    environment:
      - COUCHBASE_NODE_NAME=user-follows-product
      - COUCHBASE_CLUSTER_NAME=user-follows-product-cluster
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=followed_products
      - COUCHBASE_BUCKET_PASSWORD=123321
      - COUCHBASE_RBAC_USERNAME=myapp
      - COUCHBASE_RBAC_PASSWORD=123321
      - COUCHBASE_RBAC_PASSWORD=bucket_full_access[followed_products]

  user-follows-product:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8887:8887
    restart: always
    depends_on:
      - db
      - kafka
